[사용자 정의 데이터셋]  

- torch.utils.data.Dataset을 상속받아 직접 커스텀 데이터셋 생성  
- torch.utils.data.Dataset은 미완성의 추상 클래스(Abstract Class)

! 반드시 구현 해야하는 메서드들
* def _ _init_ _(self) : 데이터셋 전처리 / 초기화 메서드
* def _ _len_ _(self) : 데이터셋 길이 반환 메서드
* def _ _getitem_ _(self) : idx 해당 데이터 1개 반환하는 메서드 

In [1]:
# [1-1] 모듈 로딩
import torch
import torch.functional as F
from torch.utils.data import Dataset	# 인공신경망 관련 클래스 메서드
from torch.utils.data import DataLoader	# 인공신경망 관련 클래스 메서드

In [2]:
# [1-2] Custom Dataset 생성
class CustomDataset(Dataset):
	# 초기화
	def __init__(self):
		self.x_data = [[73, 80, 75],
				 	   [93, 88, 93],
					   [89, 91, 90],
					   [96, 98, 100],
					   [73, 66, 70]]
		self.y_data = [[152],
				 	   [185],
					   [180],
					   [196],
					   [142]]
		
	# 총 데이터의 개수 리턴
	def __len__(self):
		print('__len__')
		return len(self.x_data)
	
	# 인덱스에 해당하는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
	def __getitem__(self, idx):
		print(f'__getitem__{idx}')
		x = torch.FloatTensor(self.x_data[idx])
		y = torch.FloatTensor(self.y_data[idx])
		return x, y

In [3]:
## [1-3] Dataset 객체 생성
dataset = CustomDataset()

In [4]:
# 생성된 객체 확인
print(len(dataset))
print(dataset[1])

__len__
5
__getitem__1
(tensor([93., 88., 93.]), tensor([185.]))


[ DataLoader로 데이터 로딩 ]

In [5]:
# [2-1] DataLoader 객체 속성들
d_loader = DataLoader(dataset, batch_size=2, shuffle=True)

__len__
__len__


In [6]:
# [2-2] DataLoader 객체 속성들

# 한 번에 학습할 데이터량
print(d_loader.batch_size)

# 학습에 사용할 데이터셋
print(d_loader.dataset.x_data)
print(d_loader.dataset.y_data)

2
[[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
[[152], [185], [180], [196], [142]]


In [7]:
# [2-3] 데이터 추출
for feature, label in d_loader:
	print(feature, label, sep='\n')
	break

__len__
__len__
__getitem__4
__getitem__2
tensor([[73., 66., 70.],
        [89., 91., 90.]])
tensor([[142.],
        [180.]])
